creating-threads/basic-example-of-creating-thread.c:
	gcc creating-threads/basic-example-of-creating-thread.c -o ct_beoct -lpthread

creating-threads/creating-detached-thread_with_attr.c:
	gcc creating-thread/creating-detached-thread-with_attr.c -o ct_cdtw -lpthread